cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'ack'
brew 'coreutils'
brew 'git'
brew 'jq'
brew 'wget'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'spotify'
cask 'zoomus'
cask 'keybase'
